### PR TITLE
UI to edit the menu JSON

### LINKED ISSUE #10: UI to edit the menu JSON
Currently, the menu can be configured by sending a POST request. Users should be able to add or edit that JSON from a visual interface.

### PR DESCRIPTION
**Pull request by evamillan**
This PR adds a user interface at `/app/bitergia_analytics` to edit the menu's JSON. The link can be found at the sidebar under "Management".
The JSON is validated on the server side against a schema and will show an error if the validation fails.
Unsaved changes can be reverted with the "cancel changes" button.

Closes #10

### CODE REVIEW

**Review by sduenas — COMMENTED** [review]
I tested the plugin and it works as expected. However I have some comments:

-  When there's no menu preloaded, the plugin fails because it can't find it. Is there anything we can do to prevent this situation? Maybe to load an empty text area to set the json?
- When there's an invalid key we get this kind of message `[request body.metadashboard.1.dashboards.0.test]: definition for this key is missing`. I think the message is ok but, is there anyway to have something more clear for the end user?

**Comment by evamillan** [comment]
@evamillan I've fixed the issue with the non preloaded menu and improved the error messages.

**Review by sduenas — CHANGES_REQUESTED** [review]
We found the following errors testing the PR:

- The text area should have a preloaded template that users can edit. Now, it's a placeholder that can't be edited and copied.

- The app gives an error saying the `metadashboard` document already exists when clicking on `Save changes`:
imagen
 
 - When the format of the `metadashboard` field it isn't the expected one and the app is loaded again, it crashes and shows the following error.

imagen

**Comment by evamillan** [comment]
@sduenas I updated the PR, this should fix all the issues you mentioned.

**Review by sduenas — APPROVED** [review]
LGTM

**Pull request closed without merging**
